#!/bin/bash
# session-summary.sh - Generate session summary on exit
# Part of Strike UI Plugin v1.7.0

set -euo pipefail

# Configuration
STRIKE_ROOT="${STRIKE_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
SESSION_DIR="$STRIKE_ROOT/.claude/.strike"
SUMMARY_FILE="$SESSION_DIR/session-summary.md"

# Create directory if needed
mkdir -p "$SESSION_DIR"

# Gather statistics
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
SESSION_ID="${CLAUDE_SESSION_ID:-unknown}"

# Count files created
FILES_WRITTEN=0
if [ -f "$SESSION_DIR/file-operations.log" ]; then
    FILES_WRITTEN=$(grep -c "Wrote:" "$SESSION_DIR/file-operations.log" 2>/dev/null || echo "0")
fi

# Count events
EVENTS_COUNT=0
if [ -f "$SESSION_DIR/events.jsonl" ]; then
    EVENTS_COUNT=$(wc -l < "$SESSION_DIR/events.jsonl" 2>/dev/null || echo "0")
fi

# Generate summary
cat > "$SUMMARY_FILE" << EOF
# Strike UI Session Summary

**Timestamp:** $TIMESTAMP
**Session ID:** $SESSION_ID

---

## Session Statistics

| Metric | Count |
|--------|-------|
| Files Written | $FILES_WRITTEN |
| Events Logged | $EVENTS_COUNT |

---

## Session Artifacts

| File | Purpose |
|------|---------|
EOF

# List existing artifacts
for file in "$SESSION_DIR"/*.md "$SESSION_DIR"/*.json 2>/dev/null; do
    if [ -f "$file" ]; then
        basename_file=$(basename "$file")
        case "$basename_file" in
            session-summary.md) continue ;;
            *)
                echo "| \`$basename_file\` | $(head -1 "$file" 2>/dev/null | cut -c1-60 || echo "N/A") |" >> "$SUMMARY_FILE"
                ;;
        esac
    fi
done

cat >> "$SUMMARY_FILE" << EOF

---

## Next Steps

1. Review generated artifacts in \`$SESSION_DIR/\`
2. Check build results in \`./output/\`
3. Run \`/ui --resume\` to continue from checkpoint if needed

---
*Generated by Strike UI Plugin v1.7.0*
EOF

exit 0
